//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILG.DS.Profile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ILG.DS.Profile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_b_16 {
            get {
                object obj = ResourceManager.GetObject("close_b_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_gear {
            get {
                object obj = ResourceManager.GetObject("database-gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ************************************************************************************
        ///-- DS Scripts
        ///-- DBCreation
        ///-- Version 2.0
        ///-- (C) Copyright By Irakli Lomidze 2007-2023
        ///-- ************************************************************************************
        ///
        ///USE [master]
        ///GO
        ///
        ///
        ///CREATE DATABASE [__DBNAME__]
        /// CONTAINMENT = NONE
        /// ON  PRIMARY 
        ///( NAME = N&apos;__DBNAME___Data&apos;, FILENAME = N&apos;__PATH__\__DBNAME___data.mdf&apos; , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
        /// FILEGROUP [Blobs]  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBCreation {
            get {
                return ResourceManager.GetString("DBCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ************************************************************************************
        ///-- DS Scripts
        ///-- Data Seeders
        ///-- Version 2.0
        ///-- (C) Copyright By Irakli Lomidze 2007-2023
        ///-- ************************************************************************************
        ///
        ///USE [__DBNAME__]
        ///GO
        ///SET IDENTITY_INSERT [dbo].[CodexDS_DAuthor] ON 
        ///GO
        ///INSERT [dbo].[CodexDS_DAuthor] ([A_ID], [A_ORDER], [A_CAPTION]) VALUES (0, 0, N&apos;                                                                                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBSeeders {
            get {
                return ResourceManager.GetString("DBSeeders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ************************************************************************************
        ///-- DS Scripts
        ///-- Create Database 
        ///-- Version 2.0
        ///-- (C) Copyright By Irakli Lomidze 2007-2023
        ///-- ************************************************************************************
        ///
        ///USE [__DBNAME__]
        ///GO
        ////****** Object:  Table [dbo].[Codex_Formats]    Script Date: 4/4/2023 12:31:01 PM ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [dbo].[Codex_Formats](
        ///	[F_ID] [int] IDENTITY(0,1) NOT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBStructure {
            get {
                return ResourceManager.GetString("DBStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ************************************************************************************
        ///-- DS Scripts
        ///-- Users Creation
        ///-- Version 2.0
        ///-- (C) Copyright By Irakli Lomidze 2007-2023
        ///-- ************************************************************************************
        ///
        ///USE [__DBNAME__]
        ///if exists (select * from sys.schemas where name = N&apos;__DBUSERNAME__&apos;)
        ///	DROP SCHEMA  __DBUSERNAME__
        ///
        ///USE [__DBNAME__]
        ///if exists (select * from dbo.sysusers where name = N&apos;__DBUSERNAME__&apos; and uid &lt; 16382)
        ///	DROP USER  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBUsers {
            get {
                return ResourceManager.GetString("DBUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsbehaviour {
            get {
                object obj = ResourceManager.GetObject("dsbehaviour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsdocument {
            get {
                object obj = ResourceManager.GetObject("dsdocument", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsstaticdata {
            get {
                object obj = ResourceManager.GetObject("dsstaticdata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ************************************************************************************
        ///-- DS Scripts
        ///-- Full Text
        ///-- Version 2.0
        ///-- (C) Copyright By Irakli Lomidze 2007-2023
        ///-- ************************************************************************************
        ///
        ///DECLARE @IsFullTextInstalled int
        ///SET @IsFullTextInstalled = (SELECT FULLTEXTSERVICEPROPERTY(&apos;IsFullTextInstalled&apos;))
        ///
        ///IF (@IsFullTextInstalled &lt;&gt; 1)
        ///BEGIN
        /// RAISERROR (&apos;Full Text is not installed on SQL Server&apos;,0,0);
        ///END
        ///
        ///USE [__DBNAME [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FullText {
            get {
                return ResourceManager.GetString("FullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] History_Role {
            get {
                object obj = ResourceManager.GetObject("History_Role", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Role {
            get {
                object obj = ResourceManager.GetObject("Role", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
